### ISSUE TITLE
Paste as text (leaving out any formatting)

### ISSUE THREAD

**Issue by Bartman0** [mattDavo/Yippy#15] opened 2020-10-18 13:50 UTC
It would be nice to have the option to paste as text, and text only.
So leaving out any formatting, effectively paste matching target style.

There is a workaround at this moment:
1. paste desired item (positions the paste item as the current/default item)
2. Cmd-Z (remove formatted entry again)
3. Shift-Option-Cmd-V (paste matching target style, or text only; using the current/default item)

But a more direct approach would be nice.

**Comment by karlhorky** [comment] 2021-01-15 11:35
This feature would be great!

I thought that these "Shows / Pastes Rich Text" options indicated this feature, but I see no difference if I uncheck both of them (also tried restarting Yippy):

![Screen Shot 2021-01-15 at 12 33 06](https://user-images.githubusercontent.com/1935696/104722398-0ccff700-572e-11eb-9486-08093806cd6c.png)

**Comment by mattDavo** [comment] 2021-01-17 22:06
Sorry yes, I think it got broken. I will investigate!

**Comment by mattDavo** [comment] 2021-01-18 10:50
I have added more pasteboard type exclusions in [2.5.0](https://github.com/mattDavo/Yippy/releases/tag/2.5.0) Let me know of any cases (copy sources) that this does not work for @karlhorky.

**Comment by karlhorky** [comment] 2021-01-18 10:56
Oh, this restricts the pasteboard types, so that rich text copies do not even show up at all in Yippy? Ah, I think this is not what I'm looking for (maybe also not what @Bartman0 is looking for).

I was looking for something that strips formatting of text:

- copy rich text
- paste plain text

**Comment by mattDavo** [comment] 2021-01-18 10:58
Nah, they should show up if you have "Shows rich text" enabled but not paste rich text if "Pastes rich text" is disabled.

**Comment by karlhorky** [comment] 2021-01-18 11:03
Oh, ok - I guess it should work then how I imagined? I'll give `2.5.0` a shot!

**Comment by mattDavo** [comment] 2021-01-18 11:05
I hope so 😅

**Comment by karlhorky** [comment] 2021-01-18 11:09
Ok, "Pastes rich text" works 🎉

Not sure that "Shows rich text" is working - I have it unchecked, but it's still showing entries which have the rich text in my comment above:

![Screen Shot 2021-01-18 at 12 08 46](https://user-images.githubusercontent.com/1935696/104907845-fc19be00-5985-11eb-87f6-4b687a3e9a07.png)

Although, it's not showing the formatting in the visual display of Yippy - but it doesn't do this regardless of the state of this option.

**Comment by mattDavo** [comment] 2021-01-18 11:19
> Ok, disabling "Pastes rich text" works 🎉 It strips the formatting.

Sweet!

> Not sure that "Shows rich text" is working - I have it unchecked, but it's still showing entries which have the rich text in my comment above:

Yeah, maybe this isn't very clear, but this option does not affect what items are stored, but rather how they are displayed. Having it unchecked should just achieve consistent formatting, unlike this with it checked:

<img width="369" alt="Screen Shot 2021-01-18 at 10 15 19 pm" src="https://user-images.githubusercontent.com/13739650/104908487-a8858f80-59da-11eb-981d-afc03f5e6859.png">

In comparison to:

<img width="369" alt="Screen Shot 2021-01-18 at 10 17 59 pm" src="https://user-images.githubusercontent.com/13739650/104908761-074b0900-59db-11eb-90d8-01e3e3799852.png">

> Although, it's not showing the formatting in the visual display of Yippy - but it doesn't do this regardless of the state of this option.

Hmm that's very strange. Are you sure they have rich text data?

**Comment by karlhorky** [comment] 2021-01-18 11:35
> Ok, disabling "Pastes rich text" works 🎉 It strips the formatting.

Ah, maybe spoke too soon? Just tried copying / pasting multiple lines with this document and it's copying the color and formatting info:

https://docs.google.com/document/d/e/2PACX-1vSW0GMz8SVLO5vogG3sIU3yALW9q9o-k2pCt1GdrgN4namECaLRQ-9H7rsV7HahToDV_rKfVzEB_jn1/pub

**Comment by mattDavo** [comment] 2021-01-18 19:45
Ok cheers, will check it out today 👌

**Comment by mattDavo** [comment] 2021-01-19 09:55
Hmm @karlhorky would you be able to send a video of exactly how you're doing it? I can't seem to reproduce it...

**Comment by karlhorky** [comment] 2021-01-19 13:57
Ok, here's a video: https://www.youtube.com/watch?v=4vQ5blDUIwA

I also gave you edit access to the Google Doc.

**Comment by mattDavo** [comment] 2021-06-26 05:11
Resolved in https://github.com/mattDavo/Yippy/releases/tag/2.8.0

**Closed by mattDavo** 2021-06-26 05:11 UTC
Labels: bug, medium priority

**Comment by karlhorky** [comment] 2021-06-26 08:46
Cool, looks like the formatting is gone! Thanks!
